/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Register a new user.
     */
    post: operations["register_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Login with email and password to get access and refresh tokens.
     */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh
     * @description Refresh access token using refresh token.
     */
    post: operations["refresh_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Logout user by deleting refresh session and clearing cookie.
     */
    post: operations["logout_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Current User Info
     * @description Get current authenticated user information.
     */
    get: operations["get_current_user_info_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wedding/invite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Invite
     * @description Generate a signed invite link for the partner to join this wedding.
     */
    post: operations["create_invite_wedding_invite_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/wedding/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get My Wedding
     * @description Get the current user's wedding and its members.
     */
    get: operations["get_my_wedding_wedding_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/guests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Guests
     * @description List all guests for the authenticated user's wedding.
     */
    get: operations["list_guests_guests_get"];
    put?: never;
    /**
     * Create Guest
     * @description Create a new guest for the authenticated user's wedding.
     */
    post: operations["create_guest_guests_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/guests/{guest_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Guest
     * @description Delete a guest belonging to the authenticated user's wedding.
     */
    delete: operations["delete_guest_guests__guest_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Guest
     * @description Partially update a guest belonging to the authenticated user's wedding.
     */
    patch: operations["update_guest_guests__guest_id__patch"];
    trace?: never;
  };
  "/guests/{guest_id}/invite-message": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Invite Message
     * @description Generate personalized WhatsApp invite message variations for a guest using AI.
     */
    post: operations["generate_invite_message_guests__guest_id__invite_message_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/guests/{guest_id}/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Chat Invite
     * @description Conversational invite writer — returns next chatbot message or final invite.
     */
    post: operations["chat_invite_guests__guest_id__chat_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health_check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Health check endpoint to verify API is running.
     *
     *     Args:
     *         check_db: If True, also checks database connectivity
     */
    get: operations["health_check_health_check_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ChatMessage */
    ChatMessage: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Content */
      content: string;
    };
    /** ChatRequest */
    ChatRequest: {
      /** History */
      history: components["schemas"]["ChatMessage"][];
    };
    /** ChatResponse */
    ChatResponse: {
      /** Message */
      message: string;
      /** Is Complete */
      is_complete: boolean;
      /** Invite Text */
      invite_text?: string | null;
      /** Fields To Update */
      fields_to_update?: {
        [key: string]: string | null;
      } | null;
    };
    /** GuestCreate */
    GuestCreate: {
      /** Name */
      name: string;
      /** Age Group */
      age_group?: string | null;
      /** Nickname */
      nickname?: string | null;
      /** Relationship Type */
      relationship_type?: string | null;
      /** Friendship Level */
      friendship_level?: string | null;
      /** Intimacy */
      intimacy?: string | null;
      /** Contact Frequency */
      contact_frequency?: string | null;
      /** Last Contact Medium */
      last_contact_medium?: string | null;
      /** City */
      city?: string | null;
      /** State */
      state?: string | null;
      /**
       * Is Distant
       * @default false
       */
      is_distant: boolean;
      /** Memory */
      memory?: string | null;
      /** Shared Element */
      shared_element?: string | null;
      /** Ideal Tone */
      ideal_tone?: string | null;
      /** Notes */
      notes?: string | null;
      /**
       * Invite Status
       * @default pending
       */
      invite_status: string;
      /**
       * Response Status
       * @default pending
       */
      response_status: string;
    };
    /** GuestList */
    GuestList: {
      /** Guests */
      guests: components["schemas"]["GuestRead"][];
    };
    /** GuestRead */
    GuestRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Wedding Id
       * Format: uuid
       */
      wedding_id: string;
      /** Name */
      name: string;
      /** Age Group */
      age_group?: string | null;
      /** Nickname */
      nickname?: string | null;
      /** Relationship Type */
      relationship_type?: string | null;
      /** Friendship Level */
      friendship_level?: string | null;
      /** Intimacy */
      intimacy?: string | null;
      /** Contact Frequency */
      contact_frequency?: string | null;
      /** Last Contact Medium */
      last_contact_medium?: string | null;
      /** City */
      city?: string | null;
      /** State */
      state?: string | null;
      /** Is Distant */
      is_distant: boolean;
      /** Memory */
      memory?: string | null;
      /** Shared Element */
      shared_element?: string | null;
      /** Ideal Tone */
      ideal_tone?: string | null;
      /** Notes */
      notes?: string | null;
      /** Invite Status */
      invite_status: string;
      /** Response Status */
      response_status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** GuestUpdate */
    GuestUpdate: {
      /** Name */
      name?: string | null;
      /** Age Group */
      age_group?: string | null;
      /** Nickname */
      nickname?: string | null;
      /** Relationship Type */
      relationship_type?: string | null;
      /** Friendship Level */
      friendship_level?: string | null;
      /** Intimacy */
      intimacy?: string | null;
      /** Contact Frequency */
      contact_frequency?: string | null;
      /** Last Contact Medium */
      last_contact_medium?: string | null;
      /** City */
      city?: string | null;
      /** State */
      state?: string | null;
      /** Is Distant */
      is_distant?: boolean | null;
      /** Memory */
      memory?: string | null;
      /** Shared Element */
      shared_element?: string | null;
      /** Ideal Tone */
      ideal_tone?: string | null;
      /** Notes */
      notes?: string | null;
      /** Invite Status */
      invite_status?: string | null;
      /** Response Status */
      response_status?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InviteMessageResponse */
    InviteMessageResponse: {
      /**
       * Guest Id
       * Format: uuid
       */
      guest_id: string;
      /** Variations */
      variations: components["schemas"]["InviteMessageVariation"][];
    };
    /** InviteMessageVariation */
    InviteMessageVariation: {
      /** Tone */
      tone: string;
      /** Message */
      message: string;
    };
    /** InviteTokenResponse */
    InviteTokenResponse: {
      /** Invite Token */
      invite_token: string;
      /** Invite Url */
      invite_url: string;
    };
    /**
     * Token
     * @description Token response schema.
     */
    Token: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token?: string | null;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /**
     * UserCreate
     * @description Schema for creating a new user.
     */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Full Name */
      full_name?: string | null;
      /** Password */
      password: string;
      /** Invite Token */
      invite_token?: string | null;
    };
    /**
     * UserRead
     * @description Schema for reading user data.
     */
    UserRead: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Full Name */
      full_name?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Wedding Id */
      wedding_id?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WeddingMemberRead */
    WeddingMemberRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Full Name */
      full_name: string | null;
    };
    /** WeddingWithMembers */
    WeddingWithMembers: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Members */
      members: components["schemas"]["WeddingMemberRead"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
    };
  };
  logout_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  get_current_user_info_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
    };
  };
  create_invite_wedding_invite_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteTokenResponse"];
        };
      };
    };
  };
  get_my_wedding_wedding_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WeddingWithMembers"];
        };
      };
    };
  };
  list_guests_guests_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GuestList"];
        };
      };
    };
  };
  create_guest_guests_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GuestCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GuestRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_guest_guests__guest_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        guest_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_guest_guests__guest_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        guest_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GuestUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GuestRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_invite_message_guests__guest_id__invite_message_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        guest_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteMessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_invite_guests__guest_id__chat_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        guest_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_health_check_get: {
    parameters: {
      query?: {
        check_db?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string | boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
