"""add guests table

Revision ID: a973fbe23ccb
Revises: ac958052fdc8
Create Date: 2026-03-29 22:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a973fbe23ccb'
down_revision: Union[str, None] = 'ac958052fdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wedding_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_distant', sa.Boolean(), nullable=False),
    sa.Column('friendship_level', sa.String(length=100), nullable=True),
    sa.Column('intimacy', sa.String(length=100), nullable=True),
    sa.Column('contact_frequency', sa.String(length=100), nullable=True),
    sa.Column('last_contact_medium', sa.String(length=100), nullable=True),
    sa.Column('ideal_tone', sa.String(length=100), nullable=True),
    sa.Column('memory', sa.Text(), nullable=True),
    sa.Column('shared_element', sa.Text(), nullable=True),
    sa.Column('invite_status', sa.String(length=50), nullable=False),
    sa.Column('response_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    op.create_index(op.f('ix_guests_wedding_id'), 'guests', ['wedding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guests_wedding_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_table('guests')
    # ### end Alembic commands ###
